import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerAnalysisTools } from './analysis.js';
import { registerAntiDebugTools } from './antidebug.js';
import { registerBreakpointTools } from './breakpoints.js';
import { registerCommandTools } from './command.js';
import { registerControlFlowTools } from './controlflow.js';
import { registerCryptoTools } from './crypto.js';
import { registerDebugTools } from './debug.js';
import { registerDisassemblyTools } from './disassembly.js';
import { registerDumpingTools } from './dumping.js';
import { registerExceptionTools } from './exceptions.js';
import { registerGuiTools } from './gui.js';
import { registerHandleTools } from './handles.js';
import { registerMemoryTools } from './memory.js';
import { registerModuleTools } from './modules.js';
import { registerPatchTools } from './patches.js';
import { registerPeTools } from './pe.js';
import { registerProcessTools } from './process.js';
import { registerRegisterTools } from './registers.js';
import { registerSearchTools } from './search.js';
import { registerSnapshotTools } from './snapshot.js';
import { registerStackTools } from './stack.js';
import { registerSymbolTools } from './symbols.js';
import { registerTelemetryTools } from './telemetry.js';
import { registerThreadTools } from './threads.js';
import { registerTracingTools } from './tracing.js';
import { registerCrashTools } from './crash.js';
import { registerPebTools } from './peb.js';
import { registerSyscallTools } from './syscalls.js';
import { registerHeapTools } from './heap.js';
import { registerPrimitiveTools } from './primitives.js';
import { registerConfigTools } from './config.js';
import { registerTaintTools } from './taint.js';
import { registerBatchTools } from './batch.js';
import { registerYaraTools } from './yara.js';
import { registerShellcodeTools } from './shellcode.js';
import { registerDiffingTools } from './diffing.js';
import { registerResourceTools } from './resources.js';
import { registerVehTools } from './veh.js';
import { registerIatHashTools } from './iathash.js';
import { registerEtwAmsiTools } from './etw_amsi.js';
import { registerUnpackerTools } from './unpacker.js';
import { registerAuditTools } from './audit.js';
import { registerSessionTools } from './session.js';
import { registerSecurityTools } from './security.js';
import { registerCorruptionTools } from './corruption.js';
import { registerExploitPrimitivesTools } from './exploit_primitives.js';
import { registerObfuscationTools } from './obfuscation.js';
import { registerAntiDebugAdvancedTools } from './antidebug_advanced.js';
import { registerFuzzingTools } from './fuzzing.js';
import { registerSymbolicTools } from './symbolic.js';
import { registerDiffingEnhancedTools } from './diffing_enhanced.js';
import { registerKernelTools } from './kernel.js';
import { registerApiLoggerTools } from './api_logger.js';
import { registerInjectionTools } from './injection.js';
import { registerMemoryClassifierTools } from './memory_classifier.js';
import { registerRopBuilderTools } from './rop_builder.js';
import { registerStackInspectorTools } from './stack_inspector.js';
import { registerPrivescTools } from './privesc.js';
import { registerImportForgeTools } from './import_forge.js';
import { registerInstructionEmulatorTools } from './instruction_emulator.js';
import { registerBranchCoverageTools } from './branch_coverage.js';
import { registerHollowingDetectorTools } from './hollowing_detector.js';
// TIER 1 CRITICAL FEATURES
import { registerGadgetSemanticBuilderTools } from './gadget_semantic_builder.js';
import { registerIndirectResolutionTools } from './indirect_resolution.js';
import { registerHeapGadgetFinderTools } from './heap_gadget_finder.js';
import { registerSymbolicExploitFinderTools } from './symbolic_exploit_finder.js';
// TIER 2 HIGH PRIORITY FEATURES
import { registerApiDependencyGraphTools } from './api_dependency_graph.js';
import { registerStringDecryptionTools } from './string_decryption_automation.js';
import { registerJitRopAnalyzerTools } from './jit_rop_analyzer.js';
import { registerGadgetQualityScorerTools } from './gadget_quality_scorer.js';
import { registerSemanticPatcherTools } from './semantic_patcher.js';
import { registerWatchTools } from './watch.js';
import { registerScriptEngineTools } from './script_engine.js';
import { registerCodeCoverageTools } from './coverage.js';
import { registerMemwatchTools } from './memwatch.js';
import { registerStringXrefTools } from './stringxref.js';
import { registerAutoAnnotateTools } from './autoannotate.js';
import { registerVulnHuntTools } from './vulnhunt.js';
import { registerCallTreeTools } from './calltree.js';
// SPECIFICATION FEATURES 11-20
import { registerBehaviorChainExtractorTools } from './behavior_chain_extractor.js';
import { registerC2PatternAnalyzerTools } from './c2_pattern_analyzer.js';
import { registerDeadCodeAnalyzerTools } from './dead_code_analyzer.js';
import { registerSignatureGeneratorTools } from './signature_generator.js';
import { registerEncodingDetectorTools } from './encoding_detector.js';
import { registerCompressionDetectorTools } from './compression_detector.js';
import { registerExploitLikelihoodScorerTools } from './exploit_likelihood_scorer.js';
import { registerVulnChainDiscovererTools } from './vuln_chain_discoverer.js';
import { registerCodeSimilarityEngineTools } from './code_similarity_engine.js';
// ENTERPRISE ADVANCED RE & HARDWARE TOOLS
import { registerStructReconstructorTools } from './struct_reconstructor.js';
import { registerCryptoHunterTools } from './crypto_hunter.js';
import { registerComRpcWalkerTools } from './com_rpc_walker.js';
import { registerHwStateInspectorTools } from './hw_state_inspector.js';
import { registerBinaryTriagerTools } from './binary_triager.js';
// RUNTIME FORENSICS, IPC, CERT & HOTPATCH TOOLS
import { registerGolangHelperTools } from './golang_helper.js';
import { registerDotnetHelperTools } from './dotnet_helper.js';
import { registerRustHelperTools } from './rust_helper.js';
import { registerIpcMonitorTools } from './ipc_monitor.js';
import { registerCertAuthenticodeTools } from './cert_authenticode.js';
import { registerHotpatchEngineTools } from './hotpatch_engine.js';
// ADVANCED AUDITING, HYPERVISOR & FLOW TOOLS
import { registerHookScannerTools } from './hook_scanner.js';
import { registerDriverAuditorTools } from './driver_auditor.js';
import { registerExceptionTracerTools } from './exception_tracer.js';
import { registerHypervisorDetectorTools } from './hypervisor_detector.js';
import { registerFlowVisualizerTools } from './flow_visualizer.js';
// EXTENDED BINARY AUDITING, MBA, IPC & PE TOOLS (15 ADVANCED TOOLS)
import { registerPeOverlayAnalyzerTools } from './pe_overlay_analyzer.js';
import { registerDelphiHelperTools } from './delphi_helper.js';
import { registerTokenPrivilegeAuditorTools } from './token_privilege_auditor.js';
import { registerRelocationFixerTools } from './relocation_fixer.js';
import { registerCallConventionInferrerTools } from './call_convention_inferrer.js';
import { registerSymbolicEvaluatorTools } from './symbolic_evaluator.js';
import { registerNetworkSocketTrackerTools } from './network_socket_tracker.js';
import { registerEntropyHeatmapTools } from './entropy_heatmap.js';
import { registerRichHeaderAnalyzerTools } from './rich_header_analyzer.js';
import { registerFileActivityTracerTools } from './file_activity_tracer.js';
import { registerRegistryActivityTracerTools } from './registry_activity_tracer.js';
import { registerThreadStackDifferTools } from './thread_stack_differ.js';
import { registerVtableDumperTools } from './vtable_dumper.js';
import { registerModuleRebaserTools } from './module_rebaser.js';
import { registerServiceInspectorTools } from './service_inspector.js';
// 36 ADVANCED ENTERPRISE DEBUGGER & RE TOOLS (V4.5.0)
import { registerMinidumpGeneratorTools } from './minidump_generator.js';
import { registerTlsCallbackAnalyzerTools } from './tls_callback_analyzer.js';
import { registerPdbSymbolDownloaderTools } from './pdb_symbol_downloader.js';
import { registerSehUnwindTableParserTools } from './seh_unwind_table_parser.js';
import { registerResourcePayloadCarverTools } from './resource_payload_carver.js';
import { registerComTypeLibraryParserTools } from './com_type_library_parser.js';
import { registerDotnetMetadataTablesTools } from './dotnet_metadata_tables.js';
import { registerPebTebAdvancedTools } from './peb_teb_advanced.js';
import { registerFlsFiberInspectorTools } from './fls_fiber_inspector.js';
import { registerApcQueueInspectorTools } from './apc_queue_inspector.js';
import { registerJobObjectInspectorTools } from './job_object_inspector.js';
import { registerPipeDataInterceptorTools } from './pipe_data_interceptor.js';
import { registerRpcAlpcInspectorTools } from './rpc_alpc_inspector.js';
import { registerStringTableExtractorTools } from './string_table_extractor.js';
import { registerExceptionFilterTesterTools } from './exception_filter_tester.js';
import { registerMemoryPermissionWatcherTools } from './memory_permission_watcher.js';
import { registerHeapLeakDetectorTools } from './heap_leak_detector.js';
import { registerDeadlockDetectorTools } from './deadlock_detector.js';
import { registerHandleDuplicatorTools } from './handle_duplicator.js';
import { registerDllHijackAuditorTools } from './dll_hijack_auditor.js';
import { registerEntropyDeltaMonitorTools } from './entropy_delta_monitor.js';
import { registerX86X64AssemblerTools } from './x86_x64_assembler.js';
import { registerInstructionDecoderTools } from './instruction_decoder.js';
import { registerPeSecurityDirectoryTools } from './pe_security_directory.js';
import { registerDebugDirectoryParserTools } from './debug_directory_parser.js';
import { registerLoadConfigDirectoryTools } from './load_config_directory.js';
import { registerCfgGuardTableCheckerTools } from './cfg_guard_table_checker.js';
import { registerMemoryPatternReplacerTools } from './memory_pattern_replacer.js';
import { registerStringObfuscationDetectorTools } from './string_obfuscation_detector.js';
import { registerApiCallSynthesizerTools } from './api_call_synthesizer.js';
import { registerBranchTargetTracerTools } from './branch_target_tracer.js';
import { registerWindowMessageLoggerTools } from './window_message_logger.js';
import { registerEventTracingForWindowsTools } from './event_tracing_for_windows.js';
import { registerNtdllSyscallTableDumpTools } from './ntdll_syscall_table_dump.js';
import { registerSimdVectorDifferTools } from './simd_vector_differ.js';
import { registerFunctionPrototypeGeneratorTools } from './function_prototype_generator.js';
// 44 ULTRA-ADVANCED RE, FORENSICS & CONCURRENCY TOOLS (V6.0.0 - 200 MEGA-TOOLS)
import { registerMemoryRegionAliasingDetectorTools } from './memory_region_aliasing_detector.js';
import { registerVulkanDx11Dx12HookScannerTools } from './vulkan_dx11_dx12_hook_scanner.js';
import { registerGdiUserObjectInspectorTools } from './gdi_user_object_inspector.js';
import { registerWow64TransitionAnalyzerTools } from './wow64_transition_analyzer.js';
import { registerHardwareBreakpointEvasionDetectorTools } from './hardware_breakpoint_evasion_detector.js';
import { registerImportAddressTableReconstructorTools } from './import_address_table_reconstructor.js';
import { registerAppcontainerIsolationAuditorTools } from './appcontainer_isolation_auditor.js';
import { registerComMonikersInspectorTools } from './com_monikers_inspector.js';
import { registerSehScopeTableUnpackerTools } from './seh_scope_table_unpacker.js';
import { registerWin32kSyscallAuditorTools } from './win32k_syscall_auditor.js';
import { registerSehCxxCatchBlockMapperTools } from './seh_cxx_catch_block_mapper.js';
import { registerDotnetAppdomainMemoryDumperTools } from './dotnet_appdomain_memory_dumper.js';
import { registerNamedPipeImpersonationCheckerTools } from './named_pipe_impersonation_checker.js';
import { registerFlsSlotDataWalkerTools } from './fls_slot_data_walker.js';
import { registerDllExportForwarderResolverTools } from './dll_export_forwarder_resolver.js';
import { registerPeDelayLoadDirectoryParserTools } from './pe_delay_load_directory_parser.js';
import { registerComSurrogateDcomInspectorTools } from './com_surrogate_dcom_inspector.js';
import { registerStringEntropyClassifierTools } from './string_entropy_classifier.js';
import { registerDynamicStubUnfolderTools } from './dynamic_stub_unfolder.js';
import { registerHandleLeakDetectorTools } from './handle_leak_detector.js';
import { registerDriverIoctlFuzzerHarnessTools } from './driver_ioctl_fuzzer_harness.js';
import { registerAntiAntiDebugEngineTools } from './anti_anti_debug_engine.js';
import { registerStackPivotGadgetHunterTools } from './stack_pivot_gadget_hunter.js';
import { registerInstructionCycleProfilerTools } from './instruction_cycle_profiler.js';
import { registerThreadAffinityCoreMapperTools } from './thread_affinity_core_mapper.js';
import { registerIatCamouflagingDetectorTools } from './iat_camouflaging_detector.js';
import { registerPageGuardTriggerLoggerTools } from './page_guard_trigger_logger.js';
import { registerProcessMitigationPolicyViewerTools } from './process_mitigation_policy_viewer.js';
import { registerEtwEventInjectorTools } from './etw_event_injector.js';
import { registerPeExceptionDirectoryValidatorTools } from './pe_exception_directory_validator.js';
import { registerCryptoKeyScheduleTracerTools } from './crypto_key_schedule_tracer.js';
import { registerCallGraphExporterTools } from './call_graph_exporter.js';
import { registerShadowStackCetValidatorTools } from './shadow_stack_cet_validator.js';
import { registerProcessEnvironmentBlockDumperTools } from './process_environment_block_dumper.js';
import { registerPeVersionInfoParserTools } from './pe_version_info_parser.js';
import { registerMemoryHexdumpDifferTools } from './memory_hexdump_differ.js';
import { registerRopPayloadGeneratorTools } from './rop_payload_generator.js';
import { registerVehExceptionHookDebuggerTools } from './veh_exception_hook_debugger.js';
import { registerNtStatusCodeResolverTools } from './nt_status_code_resolver.js';
import { registerBranchHeatmapExporterTools } from './branch_heatmap_exporter.js';
import { registerThreadPriorityQuantumAuditorTools } from './thread_priority_quantum_auditor.js';
import { registerMemoryCommitTrackerTools } from './memory_commit_tracker.js';
import { registerSymbolicTaintFlowSynthesizerTools } from './symbolic_taint_flow_synthesizer.js';
import { registerModuleExportEntropyAnalyzerTools } from './module_export_entropy_analyzer.js';
// 50 OMNIPOTENT RE, VMM & SYSTEM INTERNALS TOOLS (V7.0.0 - 250 MEGA-TOOLS)
import { registerAslrEntropyEvaluatorTools } from './aslr_entropy_evaluator.js';
import { registerPeBoundImportDirectoryParserTools } from './pe_bound_import_directory_parser.js';
import { registerPeArchitectureDirectoryParserTools } from './pe_architecture_directory_parser.js';
import { registerPeGlobalPointerRegisterParserTools } from './pe_global_pointer_register_parser.js';
import { registerVirtualMemoryCoalescingAnalyzerTools } from './virtual_memory_coalescing_analyzer.js';
import { registerSehFilterExpressionEvaluatorTools } from './seh_filter_expression_evaluator.js';
import { registerThreadPoolWorkerInspectorTools } from './thread_pool_worker_inspector.js';
import { registerFiberLocalStorageAllocatorTools } from './fiber_local_storage_allocator.js';
import { registerComClassFactoryInspectorTools } from './com_class_factory_inspector.js';
import { registerOleDragDropDataSnifferTools } from './ole_drag_drop_data_sniffer.js';
import { registerMemoryRegionEntropyProfilerTools } from './memory_region_entropy_profiler.js';
import { registerDirectxShaderBytecodeExtractorTools } from './directx_shader_bytecode_extractor.js';
import { registerPeComDescriptorParserTools } from './pe_com_descriptor_parser.js';
import { registerClrJitCodeAllocatorTracerTools } from './clr_jit_code_allocator_tracer.js';
import { registerWow64FsRedirectionInspectorTools } from './wow64_fs_redirection_inspector.js';
import { registerWin32ClipboardDataInspectorTools } from './win32_clipboard_data_inspector.js';
import { registerMemoryPageDirtyTrackerTools } from './memory_page_dirty_tracker.js';
import { registerStackUnwindCodeDisassemblerTools } from './stack_unwind_code_disassembler.js';
import { registerDynamicCodeCaveAllocatorTools } from './dynamic_code_cave_allocator.js';
import { registerPeRichHeaderVerifierTools } from './pe_rich_header_verifier.js';
import { registerNtThreadExecutionStateAuditorTools } from './nt_thread_execution_state_auditor.js';
import { registerPipeMessageQueueDumperTools } from './pipe_message_queue_dumper.js';
import { registerFlsCallbackDispatcherTools } from './fls_callback_dispatcher.js';
import { registerInstructionDependencyAnalyzerTools } from './instruction_dependency_analyzer.js';
import { registerProcessTreeSnapshotterTools } from './process_tree_snapshotter.js';
import { registerHypervisorVmcallTrapDetectorTools } from './hypervisor_vmcall_trap_detector.js';
import { registerSehChainedUnwindHandlerTools } from './seh_chained_unwind_handler.js';
import { registerDotnetTypeSystemInspectorTools } from './dotnet_type_system_inspector.js';
import { registerCryptoStreamCipherDetectorTools } from './crypto_stream_cipher_detector.js';
import { registerDynamicBranchPredictorSimulatorTools } from './dynamic_branch_predictor_simulator.js';
import { registerComInterfaceProxyStubWalkerTools } from './com_interface_proxy_stub_walker.js';
import { registerPeExportForwarderChaserTools } from './pe_export_forwarder_chaser.js';
import { registerMemoryProtectionTransitionLoggerTools } from './memory_protection_transition_logger.js';
import { registerHardwareBreakpointCounterTools } from './hardware_breakpoint_counter.js';
import { registerWindowsHookChainAuditorTools } from './windows_hook_chain_auditor.js';
import { registerGdiFontResourceCarverTools } from './gdi_font_resource_carver.js';
import { registerAppcontainerCapabilityCheckerTools } from './appcontainer_capability_checker.js';
import { registerEtwSecurityProviderTracerTools } from './etw_security_provider_tracer.js';
import { registerSymbolicMbaRewriterTools } from './symbolic_mba_rewriter.js';
import { registerInstructionPrefixValidatorTools } from './instruction_prefix_validator.js';
import { registerThreadSynchronizationWaitChainWalkerTools } from './thread_synchronization_wait_chain_walker.js';
import { registerPeImportLookupTableValidatorTools } from './pe_import_lookup_table_validator.js';
import { registerCryptoHashStateInspectorTools } from './crypto_hash_state_inspector.js';
import { registerMemoryRegionDuplicateScannerTools } from './memory_region_duplicate_scanner.js';
import { registerProcessTokenGroupAuditorTools } from './process_token_group_auditor.js';
import { registerSehLeafFunctionUnwinderTools } from './seh_leaf_function_unwinder.js';
import { registerDriverDispatchTableDumperTools } from './driver_dispatch_table_dumper.js';
import { registerWow64CrossBitnessMemoryReaderTools } from './wow64_cross_bitness_memory_reader.js';
import { registerDirectxVtableMethodMapperTools } from './directx_vtable_method_mapper.js';
import { registerRopChainDisassemblerTools } from './rop_chain_disassembler.js';
// 50 SUPREME RE, SYSTEM INTERNALS & RUNTIME TOOLS (V8.0.0 - 300 MEGA-TOOLS)
import { registerWow64CpuContextReaderTools } from './wow64_cpu_context_reader.js';
import { registerKernelObjectSecurityDescriptorParserTools } from './kernel_object_security_descriptor_parser.js';
import { registerSehHandlerFrameValidatorTools } from './seh_handler_frame_validator.js';
import { registerSimdAvx512MaskRegisterInspectorTools } from './simd_avx512_mask_register_inspector.js';
import { registerPeEnclaveDirectoryParserTools } from './pe_enclave_directory_parser.js';
import { registerPeRelocationBlockStreamDumperTools } from './pe_relocation_block_stream_dumper.js';
import { registerMemoryPageCommitGraphExporterTools } from './memory_page_commit_graph_exporter.js';
import { registerDynamicBranchIslandAllocatorTools } from './dynamic_branch_island_allocator.js';
import { registerThreadTebStackLimitsVerifierTools } from './thread_teb_stack_limits_verifier.js';
import { registerComAggregationUnwrapperTools } from './com_aggregation_unwrapper.js';
import { registerOleClipboardFormatEnumeratorTools } from './ole_clipboard_format_enumerator.js';
import { registerDirectxHlslConstantBufferDumperTools } from './directx_hlsl_constant_buffer_dumper.js';
import { registerDotnetGarbageCollectionHeapWalkerTools } from './dotnet_garbage_collection_heap_walker.js';
import { registerWin32WindowPropInspectorTools } from './win32_window_prop_inspector.js';
import { registerHardwarePstateFrequencyEstimatorTools } from './hardware_pstate_frequency_estimator.js';
import { registerInstructionFusionAnalyzerTools } from './instruction_fusion_analyzer.js';
import { registerProcessTokenPrivilegeAdjusterTools } from './process_token_privilege_adjuster.js';
import { registerFlsFiberContextSwitcherTools } from './fls_fiber_context_switcher.js';
import { registerHypervisorTimingJitterDetectorTools } from './hypervisor_timing_jitter_detector.js';
import { registerSehCxxThrowInfoTracerTools } from './seh_cxx_throw_info_tracer.js';
import { registerCryptoAsymmetricKeyDetectorTools } from './crypto_asymmetric_key_detector.js';
import { registerMemoryWorkingSetDifferTools } from './memory_working_set_differ.js';
import { registerPeImportDelayLoadUnbinderTools } from './pe_import_delay_load_unbinder.js';
import { registerStringTableIdLookupTools } from './string_table_id_lookup.js';
import { registerProcessMitigationAcgEnforcerCheckerTools } from './process_mitigation_acg_enforcer_checker.js';
import { registerThreadIdealProcessorAssignerTools } from './thread_ideal_processor_assigner.js';
import { registerEtwTraceSessionEnumeratorTools } from './etw_trace_session_enumerator.js';
import { registerRopGadgetClusterAnalyzerTools } from './rop_gadget_cluster_analyzer.js';
import { registerMemoryGuardPageArmDisarmTools } from './memory_guard_page_arm_disarm.js';
import { registerDirectxSwapchainPresentCounterTools } from './directx_swapchain_present_counter.js';
import { registerPeExportOrdinalNameMapperTools } from './pe_export_ordinal_name_mapper.js';
import { registerGdiDcAttributeInspectorTools } from './gdi_dc_attribute_inspector.js';
import { registerSymbolicVariableRangeBounderTools } from './symbolic_variable_range_bounder.js';
import { registerWow64Peb32DumperTools } from './wow64_peb32_dumper.js';
import { registerNamedPipeSecurityCheckerTools } from './named_pipe_security_checker.js';
import { registerCryptoAesNiInstructionTracerTools } from './crypto_aes_ni_instruction_tracer.js';
import { registerInstructionSideEffectCheckerTools } from './instruction_side_effect_checker.js';
import { registerAppcontainerLoopbackPermissionCheckerTools } from './appcontainer_loopback_permission_checker.js';
import { registerThreadQuantumPriorityBoosterTools } from './thread_quantum_priority_booster.js';
import { registerMemoryPointerDerereferenceChainTracerTools } from './memory_pointer_derereference_chain_tracer.js';
import { registerSehHandlerDispatcherSimTools } from './seh_handler_dispatcher_sim.js';
import { registerDotnetSyncblkTableInspectorTools } from './dotnet_syncblk_table_inspector.js';
import { registerPeResourceManifestParserTools } from './pe_resource_manifest_parser.js';
import { registerHypervisorCpuidLeafSpoofDetectorTools } from './hypervisor_cpuid_leaf_spoof_detector.js';
import { registerDriverDeviceExtensionDumperTools } from './driver_device_extension_dumper.js';
import { registerComClassObjectRotTableInspectorTools } from './com_class_object_rot_table_inspector.js';
import { registerMemoryRegionEntropyDeltaVisualizerTools } from './memory_region_entropy_delta_visualizer.js';
import { registerInstructionBranchRunlengthProfilerTools } from './instruction_branch_runlength_profiler.js';
import { registerProcessHandleQuotaInspectorTools } from './process_handle_quota_inspector.js';
import { registerPeCoffSymbolTableParserTools } from './pe_coff_symbol_table_parser.js';
// 10 Next-Gen Exploit, VBS & Subsystem Tools
import { registerVbsHvciDetectorTools } from './vbs_hvci_detector.js';
import { registerIndirectSyscallAnalyzerTools } from './indirect_syscall_analyzer.js';
import { registerPpidSpoofDetectorTools } from './ppid_spoof_detector.js';
import { registerProcessGhostingDetectorTools } from './process_ghosting_detector.js';
import { registerTpHijackDetectorTools } from './tp_hijack_detector.js';
import { registerXsaveAvx512InspectorTools } from './xsave_avx512_inspector.js';
import { registerFormatStringAnalyzerTools } from './format_string_analyzer.js';
import { registerVmBytecodeMapperTools } from './vm_bytecode_mapper.js';
import { registerRpcInterfaceInspectorTools } from './rpc_interface_inspector.js';
import { registerWslPicoInspectorTools } from './wsl_pico_inspector.js';
// 10 Next-Generation Cutting-Edge Tools (v10.0.0)
import { registerXfgTypeHashAuditorTools } from './xfg_type_hash_auditor.js';
import { registerCetShadowStackManipulatorTools } from './cet_shadow_stack_manipulator.js';
import { registerIntelPtTracerTools } from './intel_pt_tracer.js';
import { registerSpeculativeGadgetHunterTools } from './speculative_gadget_hunter.js';
import { registerKernelCallbackAuditorTools } from './kernel_callback_auditor.js';
import { registerDsePatchguardEvaluatorTools } from './dse_patchguard_evaluator.js';
import { registerV8JitObjectInspectorTools } from './v8_jit_object_inspector.js';
import { registerCorruptedPrimitiveBuilderTools } from './corrupted_primitive_builder.js';
import { registerTlsKeyExtractorTools } from './tls_key_extractor.js';
import { registerUnrealUnityIntrospectorTools } from './unreal_unity_introspector.js';
// 10 Ultimate RE, Kernel & Runtime Tools (v11.0.0)
import { registerAmxMatrixInspectorTools } from './amx_matrix_inspector.js';
import { registerEbpfWindowsAnalyzerTools } from './ebpf_windows_analyzer.js';
import { registerEarlyApcTracerTools } from './early_apc_tracer.js';
import { registerKrnlPciDmaAuditorTools } from './krnl_pci_dma_auditor.js';
import { registerRustPanicUnwinderTools } from './rust_panic_unwinder.js';
import { registerGolangGoidSchedulerWalkerTools } from './golang_goid_scheduler_walker.js';
import { registerOepReconstructorTools } from './oep_reconstructor.js';
import { registerHypervVmbusInspectorTools } from './hyperv_vmbus_inspector.js';
import { registerKernelHandleTableParserTools } from './kernel_handle_table_parser.js';
import { registerMemoryCompressionDecoderTools } from './memory_compression_decoder.js';
// 8 Advanced Hardware, Hypervisor, Dynamic Slicing & IPC Tools (v12.0.0)
import { registerLbrBranchRingInspectorTools } from './lbr_branch_ring_inspector.js';
import { registerEptHookDetectorTools } from './ept_hook_detector.js';
import { registerCrashBackwardSlicerTools } from './crash_backward_slicer.js';
import { registerInmemorySnapshotHarnessTools } from './inmemory_snapshot_harness.js';
import { registerAlpcNdrFuzzerTools } from './alpc_ndr_fuzzer.js';
import { registerMemoryTransitionFlightRecorderTools } from './memory_transition_flight_recorder.js';
import { registerDriverIoctlProberTools } from './driver_ioctl_prober.js';
import { registerCryptoSessionHarvesterTools } from './crypto_session_harvester.js';
// 10 Deep Recon: VAD, Pool, HAL, LSASS, NTFS, KUSD, WFP, NDIS, Prefetch & Token Tools (v13.0.0)
import { registerMmvadTreeExplorerTools } from './mmvad_tree_explorer.js';
import { registerKernelPoolFengShuiTools } from './kernel_pool_feng_shui.js';
import { registerHalDispatchHijackAuditorTools } from './hal_dispatch_hijack_auditor.js';
import { registerLsassDpapiBlobReaderTools } from './lsass_dpapi_blob_reader.js';
import { registerNtfsMftArtifactCarverTools } from './ntfs_mft_artifact_carver.js';
import { registerKuserSharedDataInspectorTools } from './kuser_shared_data_inspector.js';
import { registerWfpCalloutAuditorTools } from './wfp_callout_auditor.js';
import { registerNdisLwfChainInspectorTools } from './ndis_lwf_chain_inspector.js';
import { registerPrefetchForensicsEngineTools } from './prefetch_forensics_engine.js';
import { registerTokenImpersonationChainWalkerTools } from './token_impersonation_chain_walker.js';
// 8 Unconventional Low-Level, Kernel, Forensic & Threat Suites (v14.0.0)
import { registerLegacyDebuggerTools } from './legacy_debugger_tools.js';
import { registerFirmwareUefiTools } from './firmware_uefi_tools.js';
import { registerCpuInternalsTools } from './cpu_internals_tools.js';
import { registerKernelStructuresTools } from './kernel_structures_tools.js';
import { registerInjectionPersistenceTools } from './injection_persistence_tools.js';
import { registerNetworkC2ProtocolTools } from './network_c2_protocol_tools.js';
import { registerAntiAnalysisEvasionTools } from './anti_analysis_evasion_tools.js';
import { registerMemoryForensicsDeepTools } from './memory_forensics_deep_tools.js';
import { registerBinaryAnalysisDeepTools } from './binary_analysis_deep_tools.js';
import { registerComOleMinifilterTools } from './com_ole_minifilter_tools.js';
import { registerCryptoForensicsThreatTools } from './crypto_forensics_threat_tools.js';
// 10 Deep Hardware, Virtualization & Binary Intelligence Tools (v15.0.0)
import { registerDeepBinaryVirtualizationTools } from './deep_binary_virtualization_tools.js';
// Architecture & Specialized Introspection Tools
import { registerSpecializedArchitectureTools } from './specialized_architecture_tools.js';

// DEEP RESEARCH: Modern Binary Hacking & RE 2024-2026 - Next-Gen Features (v16.0.0)
import { registerProcessInjectionEvasionDetectorTools } from './process_injection_evasion_detector.js';
import { registerTeeAnalysisTools } from './tee_analysis_tools.js';
import { registerKernelExploitPrimitivesTools } from './kernel_exploit_primitives.js';
import { registerAiAnalysisEngineTools } from './ai_analysis_engine.js';
import { registerFirmwareSecurityAnalysisTools } from './firmware_security_analysis.js';
import { registerSideChannelAnalyzerTools } from './side_channel_analyzer.js';
import { registerRustAdvancedAnalysisTools } from './rust_advanced_analysis.js';
import { registerGolangAdvancedAnalysisTools } from './golang_advanced_analysis.js';
import { registerMemoryForensicsAdvancedTools } from './memory_forensics_advanced.js';
import { registerCloudNativeAnalyzerTools } from './cloud_native_analyzer.js';

export function registerAllTools(server: McpServer) {
  registerDebugTools(server);
  registerRegisterTools(server);
  registerMemoryTools(server);
  registerDisassemblyTools(server);
  registerBreakpointTools(server);
  registerSymbolTools(server);
  registerStackTools(server);
  registerThreadTools(server);
  registerModuleTools(server);
  registerSearchTools(server);
  registerGadgetQualityScorerTools(server);
  registerSemanticPatcherTools(server);
  // Tier 1 & Tier 2 Advanced RE & Exploit Tools
  registerGadgetSemanticBuilderTools(server);
  registerIndirectResolutionTools(server);
  registerHeapGadgetFinderTools(server);
  registerSymbolicExploitFinderTools(server);
  registerApiDependencyGraphTools(server);
  registerStringDecryptionTools(server);
  registerJitRopAnalyzerTools(server);
  // New feature tools
  registerWatchTools(server);
  registerScriptEngineTools(server);
  registerCodeCoverageTools(server);
  registerMemwatchTools(server);
  registerStringXrefTools(server);
  registerAutoAnnotateTools(server);
  registerVulnHuntTools(server);
  registerCallTreeTools(server);
  registerCommandTools(server);
  registerAnalysisTools(server);
  registerTracingTools(server);
  registerDumpingTools(server);
  registerAntiDebugTools(server);
  registerExceptionTools(server);
  registerProcessTools(server);
  registerHandleTools(server);
  registerControlFlowTools(server);
  registerPatchTools(server);
  registerCryptoTools(server);
  registerPeTools(server);
  registerSnapshotTools(server);
  registerTelemetryTools(server);
  registerGuiTools(server);
  registerCrashTools(server);
  registerPebTools(server);
  registerSyscallTools(server);
  registerHeapTools(server);
  registerPrimitiveTools(server);
  registerConfigTools(server);
  registerTaintTools(server);
  registerBatchTools(server);
  registerYaraTools(server);
  registerShellcodeTools(server);
  registerDiffingTools(server);
  registerResourceTools(server);
  registerVehTools(server);
  registerIatHashTools(server);
  registerEtwAmsiTools(server);
  registerUnpackerTools(server);
  registerAuditTools(server);
  registerSessionTools(server);
  registerSecurityTools(server);
  registerCorruptionTools(server);
  registerExploitPrimitivesTools(server);
  registerObfuscationTools(server);
  registerAntiDebugAdvancedTools(server);
  registerFuzzingTools(server);
  registerSymbolicTools(server);
  registerDiffingEnhancedTools(server);
  registerKernelTools(server);
  registerApiLoggerTools(server);
  registerInjectionTools(server);
  registerMemoryClassifierTools(server);
  registerRopBuilderTools(server);
  registerStackInspectorTools(server);
  registerPrivescTools(server);
  registerImportForgeTools(server);
  registerInstructionEmulatorTools(server);
  registerBranchCoverageTools(server);
  registerHollowingDetectorTools(server);
  // Specification Features 11-20
  registerBehaviorChainExtractorTools(server);
  registerC2PatternAnalyzerTools(server);
  registerDeadCodeAnalyzerTools(server);
  registerSignatureGeneratorTools(server);
  registerEncodingDetectorTools(server);
  registerCompressionDetectorTools(server);
  registerExploitLikelihoodScorerTools(server);
  registerVulnChainDiscovererTools(server);
  registerCodeSimilarityEngineTools(server);
  // Enterprise Advanced RE & Hardware Tools
  registerStructReconstructorTools(server);
  registerCryptoHunterTools(server);
  registerComRpcWalkerTools(server);
  registerHwStateInspectorTools(server);
  registerBinaryTriagerTools(server);
  // Runtime Forensics, IPC, Cert & Hotpatch Tools
  registerGolangHelperTools(server);
  registerDotnetHelperTools(server);
  registerRustHelperTools(server);
  registerIpcMonitorTools(server);
  registerCertAuthenticodeTools(server);
  registerHotpatchEngineTools(server);
  // Advanced Auditing, Hypervisor & Flow Tools
  registerHookScannerTools(server);
  registerDriverAuditorTools(server);
  registerExceptionTracerTools(server);
  registerHypervisorDetectorTools(server);
  registerFlowVisualizerTools(server);
  // Extended Binary Auditing, MBA, IPC & PE Tools (15 Tools)
  registerPeOverlayAnalyzerTools(server);
  registerDelphiHelperTools(server);
  registerTokenPrivilegeAuditorTools(server);
  registerRelocationFixerTools(server);
  registerCallConventionInferrerTools(server);
  registerSymbolicEvaluatorTools(server);
  registerNetworkSocketTrackerTools(server);
  registerEntropyHeatmapTools(server);
  registerRichHeaderAnalyzerTools(server);
  registerFileActivityTracerTools(server);
  registerRegistryActivityTracerTools(server);
  registerThreadStackDifferTools(server);
  registerVtableDumperTools(server);
  registerModuleRebaserTools(server);
  registerServiceInspectorTools(server);
  // 36 Advanced Enterprise Debugger & RE Tools (v4.5.0)
  registerMinidumpGeneratorTools(server);
  registerTlsCallbackAnalyzerTools(server);
  registerPdbSymbolDownloaderTools(server);
  registerSehUnwindTableParserTools(server);
  registerResourcePayloadCarverTools(server);
  registerComTypeLibraryParserTools(server);
  registerDotnetMetadataTablesTools(server);
  registerPebTebAdvancedTools(server);
  registerFlsFiberInspectorTools(server);
  registerApcQueueInspectorTools(server);
  registerJobObjectInspectorTools(server);
  registerPipeDataInterceptorTools(server);
  registerRpcAlpcInspectorTools(server);
  registerStringTableExtractorTools(server);
  registerExceptionFilterTesterTools(server);
  registerMemoryPermissionWatcherTools(server);
  registerHeapLeakDetectorTools(server);
  registerDeadlockDetectorTools(server);
  registerHandleDuplicatorTools(server);
  registerDllHijackAuditorTools(server);
  registerEntropyDeltaMonitorTools(server);
  registerX86X64AssemblerTools(server);
  registerInstructionDecoderTools(server);
  registerPeSecurityDirectoryTools(server);
  registerDebugDirectoryParserTools(server);
  registerLoadConfigDirectoryTools(server);
  registerCfgGuardTableCheckerTools(server);
  registerMemoryPatternReplacerTools(server);
  registerStringObfuscationDetectorTools(server);
  registerApiCallSynthesizerTools(server);
  registerBranchTargetTracerTools(server);
  registerWindowMessageLoggerTools(server);
  registerEventTracingForWindowsTools(server);
  registerNtdllSyscallTableDumpTools(server);
  registerSimdVectorDifferTools(server);
  registerFunctionPrototypeGeneratorTools(server);
  // 44 Ultra-Advanced RE, Forensics & Concurrency Tools (v6.0.0 - 200 Mega-Tools)
  registerMemoryRegionAliasingDetectorTools(server);
  registerVulkanDx11Dx12HookScannerTools(server);
  registerGdiUserObjectInspectorTools(server);
  registerWow64TransitionAnalyzerTools(server);
  registerHardwareBreakpointEvasionDetectorTools(server);
  registerImportAddressTableReconstructorTools(server);
  registerAppcontainerIsolationAuditorTools(server);
  registerComMonikersInspectorTools(server);
  registerSehScopeTableUnpackerTools(server);
  registerWin32kSyscallAuditorTools(server);
  registerSehCxxCatchBlockMapperTools(server);
  registerDotnetAppdomainMemoryDumperTools(server);
  registerNamedPipeImpersonationCheckerTools(server);
  registerFlsSlotDataWalkerTools(server);
  registerDllExportForwarderResolverTools(server);
  registerPeDelayLoadDirectoryParserTools(server);
  registerComSurrogateDcomInspectorTools(server);
  registerStringEntropyClassifierTools(server);
  registerDynamicStubUnfolderTools(server);
  registerHandleLeakDetectorTools(server);
  registerDriverIoctlFuzzerHarnessTools(server);
  registerAntiAntiDebugEngineTools(server);
  registerStackPivotGadgetHunterTools(server);
  registerInstructionCycleProfilerTools(server);
  registerThreadAffinityCoreMapperTools(server);
  registerIatCamouflagingDetectorTools(server);
  registerPageGuardTriggerLoggerTools(server);
  registerProcessMitigationPolicyViewerTools(server);
  registerEtwEventInjectorTools(server);
  registerPeExceptionDirectoryValidatorTools(server);
  registerCryptoKeyScheduleTracerTools(server);
  registerCallGraphExporterTools(server);
  registerShadowStackCetValidatorTools(server);
  registerProcessEnvironmentBlockDumperTools(server);
  registerPeVersionInfoParserTools(server);
  registerMemoryHexdumpDifferTools(server);
  registerRopPayloadGeneratorTools(server);
  registerVehExceptionHookDebuggerTools(server);
  registerNtStatusCodeResolverTools(server);
  registerBranchHeatmapExporterTools(server);
  registerThreadPriorityQuantumAuditorTools(server);
  registerMemoryCommitTrackerTools(server);
  registerSymbolicTaintFlowSynthesizerTools(server);
  registerModuleExportEntropyAnalyzerTools(server);
  // 50 Omnipotent RE, VMM & System Internals Tools (v7.0.0 - 250 Mega-Tools)
  registerAslrEntropyEvaluatorTools(server);
  registerPeBoundImportDirectoryParserTools(server);
  registerPeArchitectureDirectoryParserTools(server);
  registerPeGlobalPointerRegisterParserTools(server);
  registerVirtualMemoryCoalescingAnalyzerTools(server);
  registerSehFilterExpressionEvaluatorTools(server);
  registerThreadPoolWorkerInspectorTools(server);
  registerFiberLocalStorageAllocatorTools(server);
  registerComClassFactoryInspectorTools(server);
  registerOleDragDropDataSnifferTools(server);
  registerMemoryRegionEntropyProfilerTools(server);
  registerDirectxShaderBytecodeExtractorTools(server);
  registerPeComDescriptorParserTools(server);
  registerClrJitCodeAllocatorTracerTools(server);
  registerWow64FsRedirectionInspectorTools(server);
  registerWin32ClipboardDataInspectorTools(server);
  registerMemoryPageDirtyTrackerTools(server);
  registerStackUnwindCodeDisassemblerTools(server);
  registerDynamicCodeCaveAllocatorTools(server);
  registerPeRichHeaderVerifierTools(server);
  registerNtThreadExecutionStateAuditorTools(server);
  registerPipeMessageQueueDumperTools(server);
  registerFlsCallbackDispatcherTools(server);
  registerInstructionDependencyAnalyzerTools(server);
  registerProcessTreeSnapshotterTools(server);
  registerHypervisorVmcallTrapDetectorTools(server);
  registerSehChainedUnwindHandlerTools(server);
  registerDotnetTypeSystemInspectorTools(server);
  registerCryptoStreamCipherDetectorTools(server);
  registerDynamicBranchPredictorSimulatorTools(server);
  registerComInterfaceProxyStubWalkerTools(server);
  registerPeExportForwarderChaserTools(server);
  registerMemoryProtectionTransitionLoggerTools(server);
  registerHardwareBreakpointCounterTools(server);
  registerWindowsHookChainAuditorTools(server);
  registerGdiFontResourceCarverTools(server);
  registerAppcontainerCapabilityCheckerTools(server);
  registerEtwSecurityProviderTracerTools(server);
  registerSymbolicMbaRewriterTools(server);
  registerInstructionPrefixValidatorTools(server);
  registerThreadSynchronizationWaitChainWalkerTools(server);
  registerPeImportLookupTableValidatorTools(server);
  registerCryptoHashStateInspectorTools(server);
  registerMemoryRegionDuplicateScannerTools(server);
  registerProcessTokenGroupAuditorTools(server);
  registerSehLeafFunctionUnwinderTools(server);
  registerDriverDispatchTableDumperTools(server);
  registerWow64CrossBitnessMemoryReaderTools(server);
  registerDirectxVtableMethodMapperTools(server);
  registerRopChainDisassemblerTools(server);
  // 50 Supreme RE, System Internals & Runtime Tools (v8.0.0 - 300 Mega-Tools)
  registerWow64CpuContextReaderTools(server);
  registerKernelObjectSecurityDescriptorParserTools(server);
  registerSehHandlerFrameValidatorTools(server);
  registerSimdAvx512MaskRegisterInspectorTools(server);
  registerPeEnclaveDirectoryParserTools(server);
  registerPeRelocationBlockStreamDumperTools(server);
  registerMemoryPageCommitGraphExporterTools(server);
  registerDynamicBranchIslandAllocatorTools(server);
  registerThreadTebStackLimitsVerifierTools(server);
  registerComAggregationUnwrapperTools(server);
  registerOleClipboardFormatEnumeratorTools(server);
  registerDirectxHlslConstantBufferDumperTools(server);
  registerDotnetGarbageCollectionHeapWalkerTools(server);
  registerWin32WindowPropInspectorTools(server);
  registerHardwarePstateFrequencyEstimatorTools(server);
  registerInstructionFusionAnalyzerTools(server);
  registerProcessTokenPrivilegeAdjusterTools(server);
  registerFlsFiberContextSwitcherTools(server);
  registerHypervisorTimingJitterDetectorTools(server);
  registerSehCxxThrowInfoTracerTools(server);
  registerCryptoAsymmetricKeyDetectorTools(server);
  registerMemoryWorkingSetDifferTools(server);
  registerPeImportDelayLoadUnbinderTools(server);
  registerStringTableIdLookupTools(server);
  registerProcessMitigationAcgEnforcerCheckerTools(server);
  registerThreadIdealProcessorAssignerTools(server);
  registerEtwTraceSessionEnumeratorTools(server);
  registerRopGadgetClusterAnalyzerTools(server);
  registerMemoryGuardPageArmDisarmTools(server);
  registerDirectxSwapchainPresentCounterTools(server);
  registerPeExportOrdinalNameMapperTools(server);
  registerGdiDcAttributeInspectorTools(server);
  registerSymbolicVariableRangeBounderTools(server);
  registerWow64Peb32DumperTools(server);
  registerNamedPipeSecurityCheckerTools(server);
  registerCryptoAesNiInstructionTracerTools(server);
  registerInstructionSideEffectCheckerTools(server);
  registerAppcontainerLoopbackPermissionCheckerTools(server);
  registerThreadQuantumPriorityBoosterTools(server);
  registerMemoryPointerDerereferenceChainTracerTools(server);
  registerSehHandlerDispatcherSimTools(server);
  registerDotnetSyncblkTableInspectorTools(server);
  registerPeResourceManifestParserTools(server);
  registerHypervisorCpuidLeafSpoofDetectorTools(server);
  registerDriverDeviceExtensionDumperTools(server);
  registerComClassObjectRotTableInspectorTools(server);
  registerMemoryRegionEntropyDeltaVisualizerTools(server);
  registerInstructionBranchRunlengthProfilerTools(server);
  registerProcessHandleQuotaInspectorTools(server);
  registerPeCoffSymbolTableParserTools(server);
  // 10 Next-Gen Exploit, VBS & Subsystem Tools
  registerVbsHvciDetectorTools(server);
  registerIndirectSyscallAnalyzerTools(server);
  registerPpidSpoofDetectorTools(server);
  registerProcessGhostingDetectorTools(server);
  registerTpHijackDetectorTools(server);
  registerXsaveAvx512InspectorTools(server);
  registerFormatStringAnalyzerTools(server);
  registerVmBytecodeMapperTools(server);
  registerRpcInterfaceInspectorTools(server);
  registerWslPicoInspectorTools(server);
  // 10 Next-Generation Cutting-Edge Tools (v10.0.0)
  registerXfgTypeHashAuditorTools(server);
  registerCetShadowStackManipulatorTools(server);
  registerIntelPtTracerTools(server);
  registerSpeculativeGadgetHunterTools(server);
  registerKernelCallbackAuditorTools(server);
  registerDsePatchguardEvaluatorTools(server);
  registerV8JitObjectInspectorTools(server);
  registerCorruptedPrimitiveBuilderTools(server);
  registerTlsKeyExtractorTools(server);
  registerUnrealUnityIntrospectorTools(server);
  // 10 Ultimate RE, Kernel & Runtime Tools (v11.0.0)
  registerAmxMatrixInspectorTools(server);
  registerEbpfWindowsAnalyzerTools(server);
  registerEarlyApcTracerTools(server);
  registerKrnlPciDmaAuditorTools(server);
  registerRustPanicUnwinderTools(server);
  registerGolangGoidSchedulerWalkerTools(server);
  registerOepReconstructorTools(server);
  registerHypervVmbusInspectorTools(server);
  registerKernelHandleTableParserTools(server);
  registerMemoryCompressionDecoderTools(server);
  // 8 Advanced Hardware, Hypervisor, Dynamic Slicing & IPC Tools (v12.0.0)
  registerLbrBranchRingInspectorTools(server);
  registerEptHookDetectorTools(server);
  registerCrashBackwardSlicerTools(server);
  registerInmemorySnapshotHarnessTools(server);
  registerAlpcNdrFuzzerTools(server);
  registerMemoryTransitionFlightRecorderTools(server);
  registerDriverIoctlProberTools(server);
  registerCryptoSessionHarvesterTools(server);
  // 10 Deep Recon: VAD, Pool, HAL, LSASS, NTFS, KUSD, WFP, NDIS, Prefetch & Token Tools (v13.0.0)
  registerMmvadTreeExplorerTools(server);
  registerKernelPoolFengShuiTools(server);
  registerHalDispatchHijackAuditorTools(server);
  registerLsassDpapiBlobReaderTools(server);
  registerNtfsMftArtifactCarverTools(server);
  registerKuserSharedDataInspectorTools(server);
  registerWfpCalloutAuditorTools(server);
  registerNdisLwfChainInspectorTools(server);
  registerPrefetchForensicsEngineTools(server);
  registerTokenImpersonationChainWalkerTools(server);
  // 8 Unconventional Low-Level, Kernel, Forensic & Threat Suites (v14.0.0)
  registerLegacyDebuggerTools(server);
  registerFirmwareUefiTools(server);
  registerCpuInternalsTools(server);
  registerKernelStructuresTools(server);
  registerInjectionPersistenceTools(server);
  registerNetworkC2ProtocolTools(server);
  registerAntiAnalysisEvasionTools(server);
  registerMemoryForensicsDeepTools(server);
  registerBinaryAnalysisDeepTools(server);
  registerComOleMinifilterTools(server);
  registerCryptoForensicsThreatTools(server);
  // 10 Deep Hardware, Virtualization & Binary Intelligence Tools (v15.0.0)
  registerDeepBinaryVirtualizationTools(server);
  // Architecture & Specialized Introspection Tools
  registerSpecializedArchitectureTools(server);
  // DEEP RESEARCH: Modern Binary Hacking & RE 2024-2026 - Next-Gen Features (v16.0.0)
  registerProcessInjectionEvasionDetectorTools(server);
  registerTeeAnalysisTools(server);
  registerKernelExploitPrimitivesTools(server);
  registerAiAnalysisEngineTools(server);
  registerFirmwareSecurityAnalysisTools(server);
  registerSideChannelAnalyzerTools(server);
  registerRustAdvancedAnalysisTools(server);
  registerGolangAdvancedAnalysisTools(server);
  registerMemoryForensicsAdvancedTools(server);
  registerCloudNativeAnalyzerTools(server);
}
