#include "plugin.h"
#include "../http_router.h"
#include <nlohmann/json.hpp>
using json = nlohmann::json;

namespace handlers {
void register_bcrypt_provider_routes(c_http_router& router) {
    router.post("/api/bcrypt/enumerate_providers", [](const httplib::Request&, httplib::Response& res) {
        json result;
        result["cng_architecture"] = {
            {"BCrypt", "CNG Primitive Provider Interface (bcrypt.dll)"},
            {"NCrypt", "CNG Key Storage Provider (KSP) Interface (ncrypt.dll)"},
            {"Router", "CNG Configuration and Provider Registration Router"}
        };
        result["default_providers"] = {
            {"Microsoft Primitive Provider", "bcrypt.dll (AES, RSA, ECDSA, SHA256, HMAC, ChaCha20)"},
            {"Microsoft Software Key Storage Provider", "ncrypt.dll (Hardware/Software DPAPI sealed keys)"},
            {"Microsoft Smart Card Key Storage Provider", "scksp.dll"},
            {"Microsoft Platform Crypto Provider", "tpmksp.dll (TPM backed keys)"}
        };
        res.set_content(result.dump(), "application/json");
    });

    router.post("/api/bcrypt/validate_provider_signatures", [](const httplib::Request&, httplib::Response& res) {
        json result;
        result["provider_verification_rules"] = {
            "1. Read registered providers from HKLM\\SYSTEM\\CurrentControlSet\\Control\\Cryptography\\Providers",
            "2. Extract ImagePath for each provider DLL",
            "3. Verify Authenticode digital signature chains to Microsoft Root CA",
            "4. Verify provider DLL is located in %WINDIR%\\System32"
        };
        res.set_content(result.dump(), "application/json");
    });

    router.post("/api/bcrypt/detect_rogue_providers", [](const httplib::Request&, httplib::Response& res) {
        json result;
        result["cng_provider_tampering_threats"] = {
            "Rogue CNG provider registration intercepts BCryptGenRandom, BCryptEncrypt, and BCryptDecrypt across all applications",
            "Malicious KSP leaks private keys generated by Microsoft CryptoAPI / CNG consumers"
        };
        res.set_content(result.dump(), "application/json");
    });
}
} // namespace handlers
