#include "plugin.h"
#include "http/c_http_router.h"
#include <nlohmann/json.hpp>
using json = nlohmann::json;

namespace handlers {
void register_smt_solver_bridge_routes(c_http_router& router) {
    router.post("/api/smt_solver/format_bitvector_formula", [](const s_http_request& req) {
        json body; try { body = json::parse(req.body); } catch(...) { body = json::object(); }
        std::string regName = body.value("target_register", "rax");
        std::string expr = body.value("expression", "(xor (bvand rax 0xFF) 0x5A)");
        
        json result;
        result["target_register"] = regName;
        result["smt2_script"] = 
            "; SMT-LIB v2.6 script generated by x64dbg-mcp\n"
            "(set-logic QF_BV)\n"
            "(declare-const " + regName + " (_ BitVec 64))\n"
            "(declare-const target_val (_ BitVec 64))\n"
            "(assert (= (bvxor (bvand " + regName + " (_ bv255 64)) (_ bv90 64)) target_val))\n"
            "(check-sat)\n"
            "(get-model)\n";
        return s_http_response::ok(result.dump());;
    });

    router.post("/api/smt_solver/generate_crackme_key_constraints", [](const s_http_request& req) {
        json result;
        result["smt2_crackme_template"] =
            "; Standard Crackme Keygen / Symbolic Constraint satisfaction template\n"
            "(set-logic QF_BV)\n"
            "(declare-const key_byte_0 (_ BitVec 8))\n"
            "(declare-const key_byte_1 (_ BitVec 8))\n"
            "(declare-const key_byte_2 (_ BitVec 8))\n"
            "(declare-const key_byte_3 (_ BitVec 8))\n"
            "; Printable ASCII constraints (0x20 <= byte <= 0x7E)\n"
            "(assert (bvuge key_byte_0 (_ bv32 8)))\n"
            "(assert (bvule key_byte_0 (_ bv126 8)))\n"
            "(assert (= (bvxor (bvadd key_byte_0 key_byte_1) (_ bv170 8)) (_ bv222 8)))\n"
            "(check-sat)\n"
            "(get-value (key_byte_0 key_byte_1))\n";
        return s_http_response::ok(result.dump());;
    });
}
} // namespace handlers

